### ISSUE TITLE
Tailwind not changing styles

### ISSUE THREAD

**Issue by MatheusBigg** [EzzEddin/fastapi-tailwindcss-jinja-sqlalchemy#1]
Hi! 

I followed your tutorial on FastAPI with Tailwind but it seems that it wont change much of the styles. 
I tried changing simple stuff like the background color, but it simply wont. 
Im kinda new o dev also, but if you could clarify it to me it would be very appreciated!

![image](https://github.com/EzzEddin/fastapi-tailwindcss-jinja-sqlalchemy/assets/103464837/a0bc8117-4b6d-46a4-bec4-593e46f0dd28)

Exemplae of purple bg but wont change the html

**Comment by EzzEddin** [comment]
Can you share the code? so that I can take a look

**Comment by MatheusBigg** [comment]
### Sure!

_Attached a note with all the codes from all files. (could not post a zip here :/ )_

**Folder structure:**
__pycache__
Include
Lib
Scripts
static
- css
- - main.css

styles
-     main.css

  
templates

-     base.html

-     navbar.html

main.py
pyenv.cfg
tailwind.config.js

Tell me if you need more, thanks a lot!
(Sorry for poor markdown, still learning here on GitHub)
[all codes.txt](https://github.com/EzzEddin/fastapi-tailwindcss-jinja-sqlalchemy/files/13449738/all.codes.txt)

**Comment by EzzEddin** [comment]
It's hard to see where the issue is in that text file. Can you share a repo instead? It would be a good practice for you though if you're still learning about development

**Comment by MatheusBigg** [comment]
Ok, here's the repo:
https://github.com/MatheusSantaFe/PokeAPP

Think i did it right

**Comment by MatheusBigg** [comment]
Man just found out!
I re-created it all and now it works. 

My mistake:
Created the root_folder and then the venv
After that cd to venv and activated it and installed the libs (inside the venv folder)
cd back and installed the pytailwindcss (outside venv folder)

Cause of that there were some 'connections' not being made i think

The right way:
root_folder and create venv
activate venv (still in root_folder)
pip install everything

And thats it! Sorry for the trouble, and many thanks!

**Comment by EzzEddin** [comment]
Great to know you've found out the issue. No trouble at all. Let me know if you face any other issues.
